apiVersion: v1
kind: Pod
metadata:
  name: web-sever-pod
  labels:
    app: web-server
    environment: production
  annotations:
      description: This the pod runs the web server
spec:
  containers:
    - name: web-server
      image: nginx:1.14.2
      ports:
        - containerPort: 80
